version: '3.8'

services:
  db:
    image: mariadb:latest
    container_name: mariadb_container
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    env_file:
      - .env

  backend:
    build: ./backend
    container_name: ktor_backend
    restart: unless-stopped
    depends_on:
      - db
    environment:
      DATABASE_URL: jdbc:mariadb://${DB_HOST}:3306/${DB_NAME}
      DATABASE_USER: ${DB_USER}
      DATABASE_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${KTOR_PORT}:8080"
    volumes:
      - ./backend:/app
    env_file:
      - .env
    command: ["gradle", "run", "--no-daemon"]
    
  frontend:
    build: ./frontend
    container_name: react_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules

    environment:
      - CHOKIDAR_USEPOLLING=true  
    depends_on:
      - backend
    command: ["npm", "run", "dev"]

volumes:
  db_data:
